spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_jB5fWTEuN
  liquibase:
    change-log: classpath:db/changelog/master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/chargenet-be
    username: chargenet
    password: WelikeElectricvehicles
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      zaxxer:
        hikari: TRACE



